In [1]:
import torch

In [2]:
class TinyModel(torch.nn.Module):
# Need to define an init function and a forward function
    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0680, -0.0892,  0.0117,  ...,  0.0187, -0.0285, -0.0270],
        [-0.0661, -0.0491,  0.0674,  ...,  0.0084,  0.0950,  0.0275],
        [ 0.0768,  0.0416,  0.0238,  ..., -0.0043,  0.0086,  0.0136],
        ...,
        [ 0.0591, -0.0660,  0.0782,  ..., -0.0105,  0.0391, -0.0868],
        [ 0.0016, -0.0743, -0.0798,  ...,  0.0945,  0.0648, -0.0100],
        [-0.0920, -0.0801, -0.0540,  ..., -0.0291,  0.0830, -0.0731]],
       requires_grad=True)
Parameter containing:
tensor([-0.0417, -0.0997, -0.0248,  0.0412, -0.0469,  0.0960, -0.0787,  0.0725,
         0.0145,  0.0833, -0.0734, -0.0133,  0.0605, -0.0339,  0.0222,  0.0737,
         0.0654,  0.0881,  0.0470,  0.04

In [3]:
# Common used layers

print('\n\n Linear Layers')
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)



 Linear Layers
Input:
tensor([[0.1943, 0.8943, 0.1394]])


Weight and Bias parameters:
Parameter containing:
tensor([[-0.1199,  0.4767,  0.0901],
        [-0.4586,  0.4353, -0.1120]], requires_grad=True)
Parameter containing:
tensor([0.1411, 0.4884], requires_grad=True)


Output:
tensor([[0.5566, 0.7729]], grad_fn=<AddmmBackward>)


In [4]:
print('\n\n Conv Layers')

import torch.functional as F


class LeNet(torch.nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = torch.nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features



 Conv Layers


In [5]:
print('\n\n RNN Layers')
class LSTMTagger(torch.nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores



 RNN Layers


In [9]:
# Other layers
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

# Normalize layer: 
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())
print(my_tensor.norm())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())
print(normed_tensor.norm())

# Dropout Layer
my_tensor = torch.rand(1, 4, 4)

dropout = torch.nn.Dropout(p=0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

# Activation Functions: ReLU and its many variants, Tanh, Hardtanh, sigmoid, and more.

# Loss Functions: Loss functions tell us how far a model’s prediction is from the correct answer. 
# PyTorch contains a variety of loss functions, including common MSE (mean squared error = L2 norm)
# Cross Entropy Loss and Negative Likelihood Loss (useful for classifiers), and others.

tensor([[[0.3398, 0.6996, 0.6616, 0.1358, 0.6247, 0.9228],
         [0.6228, 0.2028, 0.5540, 0.3011, 0.5537, 0.7178],
         [0.1623, 0.4285, 0.6397, 0.3661, 0.3067, 0.8791],
         [0.0626, 0.5759, 0.4374, 0.7948, 0.7028, 0.6805],
         [0.1293, 0.8839, 0.0658, 0.9522, 0.6942, 0.1574],
         [0.6561, 0.3933, 0.2394, 0.1451, 0.5156, 0.4543]]])
tensor([[[0.6996, 0.9228],
         [0.8839, 0.9522]]])
tensor([[[18.3486, 19.5615, 15.3849,  5.3391],
         [ 8.1349, 20.1791, 22.7153,  9.0583],
         [21.7231, 10.9834, 14.4928, 22.9845],
         [12.1806, 21.1385, 20.6928, 19.6607]]])
tensor(16.4111)
tensor(69.2585)
tensor([[[ 0.6600,  0.8770,  0.1299, -1.6669],
         [-1.0602,  0.7939,  1.1844, -0.9181],
         [ 0.8379, -1.3164, -0.6124,  1.0909],
         [-1.7132,  0.7472,  0.6247,  0.3413]]],
       grad_fn=<NativeBatchNormBackward>)
tensor(-4.0978e-08, grad_fn=<MeanBackward0>)
tensor(4.0000, grad_fn=<NormBackward0>)
