In [2]:
import torch

In [5]:
# float as default
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

# integer matrix
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

# random
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [11]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2 # every element is multiplied by 2
print(twos)

threes = ones + twos       # addition allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])
tensor([[0.8526, 0.9213, 0.2472],
        [0.1118, 0.1135, 0.0393],
        [0.5580, 0.5938, 0.1705]])


In [15]:
r = (torch.rand(2, 2) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.1029,  0.7480],
        [-0.4949,  0.3846]])

Absolute value of r:
tensor([[0.1029, 0.7480],
        [0.4949, 0.3846]])

Inverse sine of r:
tensor([[-0.1031,  0.8450],
        [-0.5177,  0.3947]])

Determinant of r:
tensor(0.3306)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.7916, -0.6110],
        [-0.6110,  0.7916]]),
S=tensor([0.9118, 0.3625]),
V=tensor([[ 0.4210, -0.9071],
        [-0.9071, -0.4210]]))

Average and standard deviation of r:
(tensor(0.5451), tensor(0.1337))

Maximum value of r:
tensor(0.7480)


In [16]:
import torch                     # for all things PyTorch
import torch.nn as nn            # for torch.nn.Module, the parent object for PyTorch models
import torch.nn.functional as F  # for the activation function

In [17]:
class LeNet(nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [26]:
net = LeNet()
print(net)                         # what does the object tell us about itself?

input = torch.rand(5, 1, 32, 32)   # stand-in for a 32x32 black & white image
print('\nImage batch shape:')
print(input.shape)

output = net(input)                # we don't call forward() directly
print('\nRaw output:')
print(output)
print(output.shape)


LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

Image batch shape:
torch.Size([5, 1, 32, 32])

Raw output:
tensor([[ 0.1110, -0.0800,  0.0402, -0.0189,  0.0525, -0.0818, -0.0231,  0.1194,
         -0.1293,  0.0556],
        [ 0.1071, -0.0834,  0.0384, -0.0150,  0.0490, -0.0816, -0.0213,  0.1185,
         -0.1257,  0.0538],
        [ 0.1103, -0.0760,  0.0388, -0.0186,  0.0519, -0.0803, -0.0196,  0.1199,
         -0.1244,  0.0554],
        [ 0.1083, -0.0768,  0.0380, -0.0200,  0.0490, -0.0812, -0.0187,  0.1190,
         -0.1259,  0.0549],
        [ 0.1083, -0.0791,  0.0414, -0.0162,  0.0491, -0.0782, -0.0242,  0.1145,
         -0.1281,  0.0577]], grad_fn=<AddmmBackward>)
torch.Size([5, 10])


In [31]:
#%matplotlib inline

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms

import matplotlib
import matplotlib.pyplot as plt
import numpy as np


ImportError: cannot import name '_has_torch_function' from 'torch._C' (/home/tianze/anaconda3/envs/ppoexample/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)