In [1]:
import torch
import math

In [5]:
x = torch.zeros(3, 4)
print(type(x))
print(x)

zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)


torch.Size([2, 2, 3])
tensor([[[1.8177e+31, 3.8946e+21, 4.4650e+30],
         [7.0975e+22, 7.2296e+31, 5.6015e-02]],

        [[7.0374e+22, 2.3534e+20, 1.1210e-43],
         [0.0000e+00, 6.7262e-44, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-6.1238e+21,  4.5908e-41, -6.1238e+21],
         [ 4.5908e-41,  7.2296e+31,  5.6015e-02]],

        [[ 7.0374e+22,  2.3534e+20,  1.1210e-43],
         [ 0.0000e+00,  6.7262e-44,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [7]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)
print(some_constants.shape)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)
print(more_integers.shape)


tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
torch.Size([2, 2])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])
torch.Size([2, 3])


In [12]:
# Math & Logic with Tensor
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)
print(ones @ twos)
print(ones * twos)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[2., 2.],
        [2., 2.]])


In [22]:
# Broadcasting. 
print(torch.tensor([[1],[2],[3],[4]]).transpose(0, 1) * 2)
rand = torch.rand(2, 4)
doubled = rand * (torch.tensor([[1],[2],[3],[4]]).transpose(0, 1) * 2)

print(rand)
print(doubled)

tensor([[2, 4, 6, 8]])
tensor([[0.2330, 0.8441, 0.9004, 0.3995],
        [0.6324, 0.9464, 0.0113, 0.5183]])
tensor([[0.4660, 3.3763, 5.4023, 3.1959],
        [1.2648, 3.7856, 0.0680, 4.1460]])


In [23]:
# tensor can detect similar shapes and apply multiplication accordingly
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.9807, 0.6545],
         [0.4144, 0.0696],
         [0.4648, 0.4491]],

        [[0.9807, 0.6545],
         [0.4144, 0.0696],
         [0.4648, 0.4491]],

        [[0.9807, 0.6545],
         [0.4144, 0.0696],
         [0.4648, 0.4491]],

        [[0.9807, 0.6545],
         [0.4144, 0.0696],
         [0.4648, 0.4491]]])
tensor([[[0.6265, 0.6265],
         [0.9411, 0.9411],
         [0.4922, 0.4922]],

        [[0.6265, 0.6265],
         [0.9411, 0.9411],
         [0.4922, 0.4922]],

        [[0.6265, 0.6265],
         [0.9411, 0.9411],
         [0.4922, 0.4922]],

        [[0.6265, 0.6265],
         [0.9411, 0.9411],
         [0.4922, 0.4922]]])
tensor([[[0.5461, 0.5396],
         [0.5461, 0.5396],
         [0.5461, 0.5396]],

        [[0.5461, 0.5396],
         [0.5461, 0.5396],
         [0.5461, 0.5396]],

        [[0.5461, 0.5396],
         [0.5461, 0.5396],
         [0.5461, 0.5396]],

        [[0.5461, 0.5396],
         [0.5461, 0.5396],
         [0.5461, 0.5396]]])


In [28]:
# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d).item())       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 3, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition


Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
2.5
tensor(1.2910)
tensor(24.)
tensor([1, 2, 3])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.3208, 0.4323],
        [0.1811, 0.6962]])
tensor([[0.9623, 1.2969],
        [0.5434, 2.0885]])
torch.return_types.svd(
U=tensor([[ 0.5907,  0.8069],
        [ 0.8069, -0.5907]]),
S=tensor([2.6500, 0.4924]),
V=tensor([[ 0.3799,  0.9250],
        [ 0.9250, -0.3799]]))


In [29]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.5675, 0.8195],
        [0.3348, 0.5565]])
tensor([[0.2126, 0.4408],
        [0.3877, 0.6078]])


In [31]:
# use clone to get a separate copy of the tensor
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# clone also copies gradient info. Use detach to turn off autograd
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

In [37]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

# create data on gpu
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

x = x.to('cpu')
print(x)



We have a GPU!
Device: cuda
tensor([[0.1132, 0.8100],
        [0.9928, 0.8932]], device='cuda:0')
tensor([[0.1132, 0.8100],
        [0.9928, 0.8932]])


In [54]:
# Manipulate tensor shape
# Note squeeze and unsqueeze can only act on dimension of extent 1
a = torch.rand(3, 226, 226)
# unsqueeze add another dimension to the input
b = a.unsqueeze(3) # add another dimension in the end
c = a.unsqueeze(0) # add another dimension in the beginning
d = a.unsqueeze(1) # add another dimension in the middle
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

# squeeze
a = torch.rand(1, 20)
print(a.shape)
print(a[0][10:])

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([3, 226, 226])
torch.Size([3, 226, 226, 1])
torch.Size([1, 3, 226, 226])
torch.Size([3, 1, 226, 226])
torch.Size([1, 20])
tensor([0.4469, 0.7223, 0.3155, 0.2655, 0.8996, 0.7969, 0.7561, 0.2476, 0.9060,
        0.4793])
torch.Size([20])
tensor([0.2657, 0.0187, 0.4910, 0.2463, 0.7342, 0.3619, 0.6786, 0.9894, 0.0748,
        0.5009, 0.4469, 0.7223, 0.3155, 0.2655, 0.8996, 0.7969, 0.7561, 0.2476,
        0.9060, 0.4793])
torch.Size([2, 2])
torch.Size([2, 2])


In [56]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

# allow broadcasting by adding another dimension by using unsqueezing
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

# reshape
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)



tensor([[[0.7415, 0.7415],
         [0.2863, 0.2863],
         [0.6553, 0.6553]],

        [[0.7415, 0.7415],
         [0.2863, 0.2863],
         [0.6553, 0.6553]],

        [[0.7415, 0.7415],
         [0.2863, 0.2863],
         [0.6553, 0.6553]],

        [[0.7415, 0.7415],
         [0.2863, 0.2863],
         [0.6553, 0.6553]]])
torch.Size([3, 1])
tensor([[[0.8176, 0.8176],
         [0.2376, 0.2376],
         [0.0161, 0.0161]],

        [[0.8176, 0.8176],
         [0.2376, 0.2376],
         [0.0161, 0.0161]],

        [[0.8176, 0.8176],
         [0.2376, 0.2376],
         [0.0161, 0.0161]],

        [[0.8176, 0.8176],
         [0.2376, 0.2376],
         [0.0161, 0.0161]]])
